### PR TITLE
Added Dependabot

### PR DESCRIPTION
**Pull request by ArnyminerZ**

### CODE REVIEW

**Comment by sunkup** [comment]
Are you sure it's a good idea to add this? Is there not a risk for the bot introducing breaking changes?

**Review by sunkup — COMMENTED** [review]
Are you sure it's a good idea to add this? Is there not a risk for the bot introducing breaking changes?

**Comment by ArnyminerZ** [comment]
> Are you sure it's a good idea to add this?

I just intend to keep this until we merge to the official repo, to keep all deps up to date without having to check every time. I think it's useful for GitHub actions though.

> Is there not a risk for the bot introducing breaking changes?

Technically shouldn't happen because we have tests, but yeah, that's why I only want to have it until we finish the refactoring. I forgot to add this to the PR description 😅

**Review by sunkup — APPROVED** [review]
Let's give this a shot then :)

**Pull request merged**
