### PR TITLE
Fix NPE on adding subscription

### LINKED ISSUE #32: NPE on adding subscription

### PR DESCRIPTION
**Pull request by sunkup**

### CODE REVIEW

**Review by ArnyminerZ — CHANGES_REQUESTED** [review]
I still don't love the idea of passing the values as `State.value`, but I guess it's the cleanest way we have.

What if we change the arguments of `LoginCredentialsComposable` to be `LiveData`? And then we observe for changes inside.

The other option would be to observe changes with
```kotlin
val requiresAuth by model.requiresAuth.observeAsState()
val username by model.username.observeAsState()
val password by model.password.observeAsState()

LoginCredentialsComposable(
    requiresAuth,
    username,
    password,
    ...
```
That way we really get rid of the NPE, and it's really the recommended approach, even though it's more lines, I think it will be more reliable.

Also, even though I don't think we should do it, if we pass directly the `MutableLiveData` to `LoginCredentialsComposable` we can update its value without having to use `onRequiresAuthChange`, `onUsernameChange` and `onPasswordChange`. Although I don't think it's a recommended approach by Compose, it's better to use the "primitive" types and callbacks.

**Comment by sunkup** [comment]
> I still don't love the idea of passing the values as `State.value`, but I guess it's the cleanest way we have.

> That way we really get rid of the NPE, and it's really the recommended approach, even though it's more lines, I think it will be more reliable.


Fair enough, I don't mind few more lines of code, as long as there is clarity - will change it :+1: 

> What if we change the arguments of `LoginCredentialsComposable` to be `LiveData`? And then we observe for changes inside.
 
> Also, even though I don't think we should do it, if we pass directly the `MutableLiveData` to `LoginCredentialsComposable` we can update its value without having to use `onRequiresAuthChange`, `onUsernameChange` and `onPasswordChange`. Although I don't think it's a recommended approach by Compose, it's better to use the "primitive" types and callbacks.

I wanted to do that quite often already :) I always think, that I can just pass the whole viewModel to the topmost composable (the old "fragment"). I think at google they don't recommend doing it, for various reasons 

- reusability of the composables - but the big topmost composable, which was a fragment earlier, usually is not re-used, so it is still a plausible Idea to have in that case ... 

- biggest problem probably is that composables can not do recomposition when livedata values are assigned/changed. That only works with state ... 

- Another possible "issue" of passing the ViewModel into the composable maybe this: The ViewModel will remain in memory while the app is alive or scoped to this composable. And if one doesn't want to use up unecessary memory, that could in theory become a problem at some point too, I guess? 

In general - even if its more code - I believe it will stay more modular and enable easier refactoring and feature adding later on. :)

**Comment by ArnyminerZ** [comment]
> Fair enough, I don't mind few more lines of code, as long as there is clarity - will change it 👍

Awesome

> In general - even if its more code - I believe it will stay more modular and enable easier refactoring and feature adding later on. :)

Yup, completely agree.

**Comment by sunkup** [comment]
> > Fair enough, I don't mind few more lines of code, as long as there is clarity - will change it 👍
> 
> Awesome
> 
> > In general - even if its more code - I believe it will stay more modular and enable easier refactoring and feature adding later on. :)
> 
> Yup, completely agree.

Can you merge it, if it looks alright to you?  There should not be any conflicts.

**Comment by ArnyminerZ** [comment]
Take a look at #36, that's what I meant 😉 

Check if you like that approach, and we can merge #36 into this and then this into dev

**Comment by sunkup** [comment]
> Take a look at #36, that's what I meant 😉
> 
> Check if you like that approach, and we can merge #36 into this and then this into dev

It does not get rid of the NPE though?

**Comment by ArnyminerZ** [comment]
> It does not get rid of the NPE though?

It should. Is it still throwing it?

**Comment by sunkup** [comment]
> > It does not get rid of the NPE though?
> 
> It should. Is it still throwing it?

yup

**Comment by ArnyminerZ** [comment]
Okay, I'll take a look

**Pull request merged**
